# Generated by Django 2.0.1 on 2020-05-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
