# Generated by Django 2.0.1 on 2020-05-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200525_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
